'use strict';

module.exports = {
    INVALID: 0,

    // Terran
    ARMORY: 29,    // CANCEL, HALT, CANCEL_LAST, RESEARCH_TERRANSHIPWEAPONS, RESEARCH_TERRANVEHICLEANDSHIPPLATING, RESEARCH_TERRANVEHICLEWEAPONS
    AUTOTURRET: 31,    // SMART, STOP, ATTACK
    BANSHEE: 55,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK, BEHAVIOR_CLOAKON, BEHAVIOR_CLOAKOFF
    BARRACKS: 21,    // SMART, TRAIN_MARINE, TRAIN_REAPER, TRAIN_GHOST, TRAIN_MARAUDER, CANCEL, HALT, CANCEL_LAST, RALLY_UNITS, LIFT, BUILD_TECHLAB, BUILD_REACTOR
    BARRACKSFLYING: 46,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, LAND, BUILD_TECHLAB, BUILD_REACTOR
    BARRACKSREACTOR: 38,    // CANCEL
    BARRACKSTECHLAB: 37,    // RESEARCH_STIMPACK, RESEARCH_COMBATSHIELD, RESEARCH_CONCUSSIVESHELLS, CANCEL, CANCEL_LAST
    BATTLECRUISER: 57,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_YAMATOGUN, EFFECT_TACTICALJUMP, STOP, ATTACK
    BUNKER: 24,    // SMART, EFFECT_SALVAGE, CANCEL, HALT, UNLOADALL, STOP, LOAD, RALLY_UNITS, ATTACK, EFFECT_STIM
    COMMANDCENTER: 18,    // SMART, TRAIN_SCV, MORPH_PLANETARYFORTRESS, MORPH_ORBITALCOMMAND, CANCEL, HALT, LOADALL, UNLOADALL, CANCEL_LAST, LIFT, RALLY_WORKERS
    COMMANDCENTERFLYING: 36,    // SMART, MOVE, PATROL, HOLDPOSITION, LOADALL, UNLOADALL, STOP, LAND
    CYCLONE: 692,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_LOCKON, CANCEL, STOP, ATTACK
    ENGINEERINGBAY: 22,    // RESEARCH_HISECAUTOTRACKING, RESEARCH_TERRANSTRUCTUREARMORUPGRADE, RESEARCH_NEOSTEELFRAME, CANCEL, HALT, CANCEL_LAST, RESEARCH_TERRANINFANTRYARMOR, RESEARCH_TERRANINFANTRYWEAPONS
    FACTORY: 27,    // SMART, TRAIN_SIEGETANK, TRAIN_THOR, TRAIN_HELLION, TRAIN_HELLBAT, TRAIN_CYCLONE, TRAIN_WIDOWMINE, CANCEL, HALT, CANCEL_LAST, RALLY_UNITS, LIFT, BUILD_TECHLAB, BUILD_REACTOR
    FACTORYFLYING: 43,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, LAND, BUILD_TECHLAB, BUILD_REACTOR
    FACTORYREACTOR: 40,    // CANCEL
    FACTORYTECHLAB: 39,    // RESEARCH_INFERNALPREIGNITER, RESEARCH_DRILLINGCLAWS, RESEARCH_RAPIDFIRELAUNCHERS, RESEARCH_SMARTSERVOS, CANCEL, CANCEL_LAST
    FUSIONCORE: 30,    // RESEARCH_BATTLECRUISERWEAPONREFIT, CANCEL, HALT, CANCEL_LAST
    GHOST: 50,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_NUKECALLDOWN, EFFECT_EMP, EFFECT_GHOSTSNIPE, CANCEL, STOP, ATTACK, BEHAVIOR_CLOAKON, BEHAVIOR_CLOAKOFF, BEHAVIOR_HOLDFIREON, BEHAVIOR_HOLDFIREOFF
    GHOSTACADEMY: 26,    // BUILD_NUKE, RESEARCH_PERSONALCLOAKING, CANCEL, HALT, CANCEL_LAST
    HELLION: 53,    // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_HELLBAT, STOP, ATTACK
    HELLIONTANK: 484,   // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_HELLION, STOP, ATTACK
    LIBERATOR: 689,   // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_LIBERATORAGMODE, STOP, ATTACK
    LIBERATORAG: 734,   // SMART, MORPH_LIBERATORAAMODE, STOP, ATTACK
    MARAUDER: 51,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK, EFFECT_STIM
    MARINE: 48,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK, EFFECT_STIM
    MEDIVAC: 54,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_HEAL, EFFECT_MEDIVACIGNITEAFTERBURNERS, STOP, LOAD, UNLOADALLAT, ATTACK
    MISSILETURRET: 23,    // SMART, CANCEL, HALT, STOP, ATTACK
    MULE: 268,   // SMART, MOVE, PATROL, HOLDPOSITION, STOP, HARVEST_GATHER, HARVEST_RETURN, ATTACK, EFFECT_REPAIR
    ORBITALCOMMAND: 132,   // SMART, EFFECT_CALLDOWNMULE, EFFECT_SUPPLYDROP, EFFECT_SCAN, TRAIN_SCV, CANCEL_LAST, LIFT, RALLY_WORKERS
    ORBITALCOMMANDFLYING: 134,   // SMART, MOVE, PATROL, HOLDPOSITION, STOP, LAND
    PLANETARYFORTRESS: 130,   // SMART, TRAIN_SCV, LOADALL, STOP, CANCEL_LAST, ATTACK, RALLY_WORKERS
    RAVEN: 56,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_POINTDEFENSEDRONE, EFFECT_HUNTERSEEKERMISSILE, EFFECT_AUTOTURRET, STOP, ATTACK
    REAPER: 49,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_KD8CHARGE, STOP, ATTACK
    REFINERY: 20,    // CANCEL, HALT
    SCV: 45,    // SMART, MOVE, PATROL, HOLDPOSITION, BUILD_COMMANDCENTER, BUILD_SUPPLYDEPOT, BUILD_REFINERY, BUILD_BARRACKS, BUILD_ENGINEERINGBAY, BUILD_MISSILETURRET, BUILD_BUNKER, BUILD_SENSORTOWER, BUILD_GHOSTACADEMY, BUILD_FACTORY, BUILD_STARPORT, BUILD_ARMORY, BUILD_FUSIONCORE, HALT, STOP, HARVEST_GATHER, HARVEST_RETURN, ATTACK, EFFECT_SPRAY, EFFECT_REPAIR
    SENSORTOWER: 25,    // CANCEL, HALT
    SIEGETANK: 33,    // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_SIEGEMODE, STOP, ATTACK
    SIEGETANKSIEGED: 32,    // SMART, MORPH_UNSIEGE, STOP, ATTACK
    STARPORT: 28,    // SMART, TRAIN_MEDIVAC, TRAIN_BANSHEE, TRAIN_RAVEN, TRAIN_BATTLECRUISER, TRAIN_VIKINGFIGHTER, TRAIN_LIBERATOR, CANCEL, HALT, CANCEL_LAST, RALLY_UNITS, LIFT, BUILD_TECHLAB, BUILD_REACTOR
    STARPORTFLYING: 44,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, LAND, BUILD_TECHLAB, BUILD_REACTOR
    STARPORTREACTOR: 42,    // CANCEL
    STARPORTTECHLAB: 41,    // RESEARCH_BANSHEECLOAKINGFIELD, RESEARCH_RAVENCORVIDREACTOR, RESEARCH_ENHANCEDMUNITIONS, RESEARCH_BANSHEEHYPERFLIGHTROTORS, RESEARCH_RAVENRECALIBRATEDEXPLOSIVES, RESEARCH_HIGHCAPACITYFUELTANKS, RESEARCH_ADVANCEDBALLISTICS, CANCEL, CANCEL_LAST
    SUPPLYDEPOT: 19,    // MORPH_SUPPLYDEPOT_LOWER, CANCEL, HALT
    SUPPLYDEPOTLOWERED: 47,    // MORPH_SUPPLYDEPOT_RAISE
    THOR: 52,    // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_THORHIGHIMPACTMODE, STOP, ATTACK
    THORAP: 691,   // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_THOREXPLOSIVEMODE, CANCEL, STOP, ATTACK
    VIKINGASSAULT: 34,    // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_VIKINGFIGHTERMODE, STOP, ATTACK
    VIKINGFIGHTER: 35,    // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_VIKINGASSAULTMODE, STOP, ATTACK
    WIDOWMINE: 498,   // SMART, MOVE, PATROL, HOLDPOSITION, BURROWDOWN, STOP, ATTACK
    WIDOWMINEBURROWED: 500,   // SMART, EFFECT_WIDOWMINEATTACK, BURROWUP

    // Terran non-interactive
    KD8CHARGE: 830,
    NUKE: 58,
    POINTDEFENSEDRONE: 11,
    REACTOR: 6,
    TECHLAB: 5,

    // Zerg
    BANELING: 9,     // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_EXPLODE, BEHAVIOR_BUILDINGATTACKON, BEHAVIOR_BUILDINGATTACKOFF, BURROWDOWN, STOP, ATTACK
    BANELINGBURROWED: 115,   // EFFECT_EXPLODE, BURROWUP
    BANELINGCOCOON: 8,     // SMART, CANCEL_LAST, RALLY_UNITS
    BANELINGNEST: 96,    // RESEARCH_CENTRIFUGALHOOKS, CANCEL, CANCEL_LAST
    BROODLING: 289,   // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    BROODLORD: 114,   // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    BROODLORDCOCOON: 113,   // SMART, MOVE, PATROL, HOLDPOSITION, CANCEL
    CHANGELING: 12,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    CHANGELINGMARINE: 15,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    CHANGELINGMARINESHIELD: 14,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    CHANGELINGZEALOT: 13,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    CHANGELINGZERGLING: 17,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    CHANGELINGZERGLINGWINGS: 16,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    CORRUPTOR: 112,   // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_BROODLORD, EFFECT_CAUSTICSPRAY, STOP, ATTACK
    CREEPTUMOR: 87,    // CANCEL
    CREEPTUMORBURROWED: 137,   // SMART, CANCEL, BUILD_CREEPTUMOR
    CREEPTUMORQUEEN: 138,   // CANCEL
    DRONE: 104,   // SMART, MOVE, PATROL, HOLDPOSITION, BUILD_HATCHERY, BUILD_EXTRACTOR, BUILD_SPAWNINGPOOL, BUILD_EVOLUTIONCHAMBER, BUILD_HYDRALISKDEN, BUILD_SPIRE, BUILD_ULTRALISKCAVERN, BUILD_INFESTATIONPIT, BUILD_NYDUSNETWORK, BUILD_BANELINGNEST, BUILD_ROACHWARREN, BUILD_SPINECRAWLER, BUILD_SPORECRAWLER, BURROWDOWN, STOP, HARVEST_GATHER, HARVEST_RETURN, ATTACK, EFFECT_SPRAY
    DRONEBURROWED: 116,   // BURROWUP
    EGG: 103,   // SMART, CANCEL_LAST, RALLY_UNITS
    EVOLUTIONCHAMBER: 90,    // CANCEL, CANCEL_LAST, RESEARCH_ZERGGROUNDARMOR, RESEARCH_ZERGMELEEWEAPONS, RESEARCH_ZERGMISSILEWEAPONS
    EXTRACTOR: 88,    // CANCEL
    GREATERSPIRE: 102,   // CANCEL_LAST, RESEARCH_ZERGFLYERARMOR, RESEARCH_ZERGFLYERATTACK
    HATCHERY: 86,    // SMART, MORPH_LAIR, RESEARCH_PNEUMATIZEDCARAPACE, RESEARCH_BURROW, TRAIN_QUEEN, CANCEL, CANCEL_LAST, RALLY_UNITS, RALLY_WORKERS
    HIVE: 101,   // SMART, RESEARCH_PNEUMATIZEDCARAPACE, RESEARCH_BURROW, TRAIN_QUEEN, CANCEL_LAST, RALLY_UNITS, RALLY_WORKERS
    HYDRALISK: 107,   // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_LURKER, BURROWDOWN, STOP, ATTACK
    HYDRALISKBURROWED: 117,   // BURROWUP
    HYDRALISKDEN: 91,    // RESEARCH_GROOVEDSPINES, RESEARCH_MUSCULARAUGMENTS, MORPH_LURKERDEN, CANCEL, CANCEL_LAST
    INFESTATIONPIT: 94,    // RESEARCH_PATHOGENGLANDS, RESEARCH_NEURALPARASITE, CANCEL, CANCEL_LAST
    INFESTEDTERRANSEGG: 150,   // SMART, MOVE, PATROL, HOLDPOSITION
    INFESTOR: 111,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_FUNGALGROWTH, EFFECT_INFESTEDTERRANS, EFFECT_NEURALPARASITE, CANCEL, BURROWDOWN, STOP, ATTACK
    INFESTORBURROWED: 127,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_FUNGALGROWTH, EFFECT_INFESTEDTERRANS, EFFECT_NEURALPARASITE, CANCEL, BURROWUP, STOP, ATTACK
    INFESTORTERRAN: 7,     // SMART, MOVE, PATROL, HOLDPOSITION, BURROWDOWN, STOP, ATTACK
    LAIR: 100,   // SMART, MORPH_HIVE, RESEARCH_PNEUMATIZEDCARAPACE, RESEARCH_BURROW, TRAIN_QUEEN, CANCEL, CANCEL_LAST, RALLY_UNITS, RALLY_WORKERS
    LARVA: 151,   // TRAIN_DRONE, TRAIN_ZERGLING, TRAIN_OVERLORD, TRAIN_HYDRALISK, TRAIN_MUTALISK, TRAIN_ULTRALISK, TRAIN_ROACH, TRAIN_INFESTOR, TRAIN_CORRUPTOR, TRAIN_VIPER, TRAIN_SWARMHOST
    LOCUSTMP: 489,   // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    LOCUSTMPFLYING: 693,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_LOCUSTSWOOP, STOP, ATTACK
    LURKERDENMP: 504,   // RESEARCH_GROOVEDSPINES, RESEARCH_MUSCULARAUGMENTS, CANCEL_LAST
    LURKERMP: 502,   // SMART, MOVE, PATROL, HOLDPOSITION, BURROWDOWN, STOP, ATTACK
    LURKERMPBURROWED: 503,   // SMART, BURROWUP, STOP, ATTACK, BEHAVIOR_HOLDFIREON, BEHAVIOR_HOLDFIREOFF
    LURKERMPEGG: 501,   // SMART, CANCEL, RALLY_UNITS
    MUTALISK: 108,   // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    NYDUSCANAL: 142,   // SMART, UNLOADALL, STOP, LOAD, RALLY_UNITS
    NYDUSNETWORK: 95,    // SMART, BUILD_NYDUSWORM, CANCEL, UNLOADALL, STOP, LOAD, RALLY_UNITS
    OVERLORD: 106,   // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_OVERSEER, BEHAVIOR_GENERATECREEPON, BEHAVIOR_GENERATECREEPOFF, MORPH_OVERLORDTRANSPORT, CANCEL, STOP, ATTACK
    OVERLORDCOCOON: 128,   // SMART, MOVE, PATROL, HOLDPOSITION, CANCEL
    OVERLORDTRANSPORT: 893,   // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_OVERSEER, BEHAVIOR_GENERATECREEPON, BEHAVIOR_GENERATECREEPOFF, STOP, LOAD, UNLOADALLAT, ATTACK
    OVERSEER: 129,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_SPAWNCHANGELING, EFFECT_CONTAMINATE, STOP, ATTACK
    QUEEN: 126,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_INJECTLARVA, EFFECT_TRANSFUSION, BURROWDOWN, STOP, ATTACK, BUILD_CREEPTUMOR
    QUEENBURROWED: 125,   // BURROWUP
    RAVAGER: 688,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_CORROSIVEBILE, BURROWDOWN, STOP, ATTACK
    RAVAGERCOCOON: 687,   // SMART, CANCEL, RALLY_UNITS
    ROACH: 110,   // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_RAVAGER, BURROWDOWN, STOP, ATTACK
    ROACHBURROWED: 118,   // SMART, MOVE, PATROL, HOLDPOSITION, BURROWUP, STOP, ATTACK
    ROACHWARREN: 97,    // RESEARCH_GLIALREGENERATION, RESEARCH_TUNNELINGCLAWS, CANCEL, CANCEL_LAST
    SPAWNINGPOOL: 89,    // RESEARCH_ZERGLINGADRENALGLANDS, RESEARCH_ZERGLINGMETABOLICBOOST, CANCEL, CANCEL_LAST
    SPINECRAWLER: 98,    // SMART, CANCEL, STOP, ATTACK, MORPH_UPROOT
    SPINECRAWLERUPROOTED: 139,   // SMART, MOVE, PATROL, HOLDPOSITION, CANCEL, STOP, ATTACK, MORPH_ROOT
    SPIRE: 92,    // MORPH_GREATERSPIRE, CANCEL, CANCEL_LAST, RESEARCH_ZERGFLYERARMOR, RESEARCH_ZERGFLYERATTACK
    SPORECRAWLER: 99,    // SMART, CANCEL, STOP, ATTACK, MORPH_UPROOT
    SPORECRAWLERUPROOTED: 140,   // SMART, MOVE, PATROL, HOLDPOSITION, CANCEL, STOP, ATTACK, MORPH_ROOT
    SWARMHOSTBURROWEDMP: 493,   // SMART, EFFECT_SPAWNLOCUSTS, BURROWUP
    SWARMHOSTMP: 494,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_SPAWNLOCUSTS, BURROWDOWN, STOP, ATTACK
    TRANSPORTOVERLORDCOCOON: 892,   // SMART, MOVE, PATROL, HOLDPOSITION, CANCEL
    ULTRALISK: 109,   // SMART, MOVE, PATROL, HOLDPOSITION, BURROWDOWN, STOP, ATTACK
    ULTRALISKCAVERN: 93,    // RESEARCH_CHITINOUSPLATING, CANCEL, CANCEL_LAST
    VIPER: 499,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_BLINDINGCLOUD, EFFECT_ABDUCT, EFFECT_VIPERCONSUME, EFFECT_PARASITICBOMB, STOP, ATTACK
    ZERGLING: 105,   // SMART, MOVE, PATROL, HOLDPOSITION, TRAIN_BANELING, BURROWDOWN, STOP, ATTACK
    ZERGLINGBURROWED: 119,   // BURROWUP

    // Zerg non-interactive
    PARASITICBOMBDUMMY: 824,

    // Protoss
    ADEPT: 311,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_ADEPTPHASESHIFT, CANCEL, STOP, RALLY_UNITS, ATTACK
    ADEPTPHASESHIFT: 801,   // SMART, MOVE, PATROL, HOLDPOSITION, CANCEL, STOP, ATTACK
    ARCHON: 141,   // SMART, MOVE, PATROL, HOLDPOSITION, STOP, RALLY_UNITS, ATTACK
    ASSIMILATOR: 61,    // CANCEL
    CARRIER: 79,    // SMART, MOVE, PATROL, HOLDPOSITION, BUILD_INTERCEPTORS, STOP, CANCEL_LAST, ATTACK
    COLOSSUS: 4,     // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    CYBERNETICSCORE: 72,    // RESEARCH_WARPGATE, CANCEL, CANCEL_LAST, RESEARCH_PROTOSSAIRARMOR, RESEARCH_PROTOSSAIRWEAPONS
    DARKSHRINE: 69,    // RESEARCH_SHADOWSTRIKE, CANCEL, CANCEL_LAST
    DARKTEMPLAR: 76,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, RALLY_UNITS, ATTACK, EFFECT_BLINK
    DISRUPTOR: 694,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_PURIFICATIONNOVA, STOP, ATTACK
    DISRUPTORPHASED: 733,   // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    FLEETBEACON: 64,    // RESEARCH_INTERCEPTORGRAVITONCATAPULT, RESEARCH_PHOENIXANIONPULSECRYSTALS, CANCEL, CANCEL_LAST
    FORGE: 63,    // CANCEL, CANCEL_LAST, RESEARCH_PROTOSSGROUNDARMOR, RESEARCH_PROTOSSGROUNDWEAPONS, RESEARCH_PROTOSSSHIELDS
    GATEWAY: 62,    // SMART, TRAIN_ZEALOT, TRAIN_STALKER, TRAIN_HIGHTEMPLAR, TRAIN_DARKTEMPLAR, TRAIN_SENTRY, TRAIN_ADEPT, MORPH_WARPGATE, CANCEL, CANCEL_LAST, RALLY_UNITS
    HIGHTEMPLAR: 75,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_FEEDBACK, EFFECT_PSISTORM, STOP, RALLY_UNITS, ATTACK
    IMMORTAL: 83,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_IMMORTALBARRIER, STOP, ATTACK
    INTERCEPTOR: 85,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    MOTHERSHIP: 10,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_PHOTONOVERCHARGE, EFFECT_TIMEWARP, STOP, ATTACK, EFFECT_MASSRECALL
    MOTHERSHIPCORE: 488,   // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_MOTHERSHIP, EFFECT_PHOTONOVERCHARGE, EFFECT_TIMEWARP, CANCEL, STOP, ATTACK, EFFECT_MASSRECALL
    NEXUS: 59,    // SMART, EFFECT_CHRONOBOOST, TRAIN_PROBE, TRAIN_MOTHERSHIP, CANCEL, CANCEL_LAST, RALLY_WORKERS
    OBSERVER: 82,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
    ORACLE: 495,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_ORACLEREVELATION, BEHAVIOR_PULSARBEAMON, BEHAVIOR_PULSARBEAMOFF, BUILD_STASISTRAP, CANCEL, STOP, ATTACK
    ORACLESTASISTRAP: 732,   // CANCEL
    PHOENIX: 78,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_GRAVITONBEAM, CANCEL, STOP, ATTACK
    PHOTONCANNON: 66,    // SMART, CANCEL, STOP, ATTACK
    PROBE: 84,    // SMART, MOVE, PATROL, HOLDPOSITION, BUILD_NEXUS, BUILD_PYLON, BUILD_ASSIMILATOR, BUILD_GATEWAY, BUILD_FORGE, BUILD_FLEETBEACON, BUILD_TWILIGHTCOUNCIL, BUILD_PHOTONCANNON, BUILD_SHIELDBATTERY, BUILD_STARGATE, BUILD_TEMPLARARCHIVE, BUILD_DARKSHRINE, BUILD_ROBOTICSBAY, BUILD_ROBOTICSFACILITY, BUILD_CYBERNETICSCORE, STOP, HARVEST_GATHER, HARVEST_RETURN, ATTACK, EFFECT_SPRAY
    PYLON: 60,    // CANCEL
    PYLONOVERCHARGED: 894,   // SMART, STOP, ATTACK
    ROBOTICSBAY: 70,    // RESEARCH_GRAVITICBOOSTER, RESEARCH_GRAVITICDRIVE, RESEARCH_EXTENDEDTHERMALLANCE, CANCEL, CANCEL_LAST
    ROBOTICSFACILITY: 71,    // SMART, TRAIN_WARPPRISM, TRAIN_OBSERVER, TRAIN_COLOSSUS, TRAIN_IMMORTAL, TRAIN_DISRUPTOR, CANCEL, CANCEL_LAST, RALLY_UNITS
    SENTRY: 77,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_GUARDIANSHIELD, HALLUCINATION_ARCHON, HALLUCINATION_COLOSSUS, HALLUCINATION_HIGHTEMPLAR, HALLUCINATION_IMMORTAL, HALLUCINATION_PHOENIX, HALLUCINATION_PROBE, HALLUCINATION_STALKER, HALLUCINATION_VOIDRAY, HALLUCINATION_WARPPRISM, HALLUCINATION_ZEALOT, EFFECT_FORCEFIELD, HALLUCINATION_ORACLE, HALLUCINATION_DISRUPTOR, HALLUCINATION_ADEPT, STOP, RALLY_UNITS, ATTACK
    SHIELDBATTERY: 1910,   // SMART, EFFECT_RESTORE
    STALKER: 74,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, RALLY_UNITS, ATTACK, EFFECT_BLINK
    STARGATE: 67,    // SMART, TRAIN_PHOENIX, TRAIN_CARRIER, TRAIN_VOIDRAY, TRAIN_ORACLE, TRAIN_TEMPEST, CANCEL, CANCEL_LAST, RALLY_UNITS
    TEMPEST: 496,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_TEMPESTDISRUPTIONBLAST, CANCEL, STOP, ATTACK
    TEMPLARARCHIVE: 68,    // RESEARCH_PSISTORM, CANCEL, CANCEL_LAST
    TWILIGHTCOUNCIL: 65,    // RESEARCH_CHARGE, RESEARCH_BLINK, RESEARCH_ADEPTRESONATINGGLAIVES, CANCEL, CANCEL_LAST
    VOIDRAY: 80,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_VOIDRAYPRISMATICALIGNMENT, STOP, ATTACK
    WARPGATE: 133,   // SMART, TRAINWARP_ZEALOT, TRAINWARP_STALKER, TRAINWARP_HIGHTEMPLAR, TRAINWARP_DARKTEMPLAR, TRAINWARP_SENTRY, TRAINWARP_ADEPT, MORPH_GATEWAY
    WARPPRISM: 81,    // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_WARPPRISMPHASINGMODE, STOP, LOAD, UNLOADALLAT, ATTACK
    WARPPRISMPHASING: 136,   // SMART, MORPH_WARPPRISMTRANSPORTMODE, STOP, LOAD, UNLOADALLAT
    ZEALOT: 73,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_CHARGE, STOP, RALLY_UNITS, ATTACK

    // Protoss non-interactive

    // Neutral
    BATTLESTATIONMINERALFIELD: 886,
    BATTLESTATIONMINERALFIELD750: 887,
    COLLAPSIBLEROCKTOWERDEBRIS: 490,
    COLLAPSIBLEROCKTOWERDIAGONAL: 588,
    COLLAPSIBLEROCKTOWERPUSHUNIT: 561,
    COLLAPSIBLETERRANTOWERDEBRIS: 485,
    COLLAPSIBLETERRANTOWERDIAGONAL: 589,
    COLLAPSIBLETERRANTOWERPUSHUNIT: 562,
    COLLAPSIBLETERRANTOWERPUSHUNITRAMPLEFT: 559,
    COLLAPSIBLETERRANTOWERPUSHUNITRAMPRIGHT: 560,
    COLLAPSIBLETERRANTOWERRAMPLEFT: 590,
    COLLAPSIBLETERRANTOWERRAMPRIGHT: 591,
    DEBRISRAMPLEFT: 486,
    DEBRISRAMPRIGHT: 487,
    DESTRUCTIBLEDEBRIS6X6: 365,
    DESTRUCTIBLEDEBRISRAMPDIAGONALHUGEBLUR: 377,
    DESTRUCTIBLEDEBRISRAMPDIAGONALHUGEULBR: 376,
    DESTRUCTIBLEROCK6X6: 371,
    DESTRUCTIBLEROCKEX1DIAGONALHUGEBLUR: 641,
    FORCEFIELD: 135,
    KARAKFEMALE: 324,
    LABMINERALFIELD: 665,
    LABMINERALFIELD750: 666,
    MINERALFIELD: 341,
    MINERALFIELD750: 483,
    PROTOSSVESPENEGEYSER: 608,
    PURIFIERMINERALFIELD: 884,
    PURIFIERMINERALFIELD750: 885,
    PURIFIERRICHMINERALFIELD: 796,
    PURIFIERRICHMINERALFIELD750: 797,
    PURIFIERVESPENEGEYSER: 880,
    RICHMINERALFIELD: 146,
    RICHMINERALFIELD750: 147,
    RICHVESPENEGEYSER: 344,
    SCANTIPEDE: 335,
    SHAKURASVESPENEGEYSER: 881,
    SPACEPLATFORMGEYSER: 343,
    UNBUILDABLEBRICKSDESTRUCTIBLE: 473,
    UNBUILDABLEPLATESDESTRUCTIBLE: 474,
    UTILITYBOT: 330,
    VESPENEGEYSER: 342,
    XELNAGATOWER: 149,
};
